local-phone-apps = ApplicationsProvider \
                   BackupRestoreConfirmation \
                   Bluetooth \
		   Browser \
		   Calculator \
		   Calendar \
		   CalendarProvider \
                   CertInstaller \
                   Contacts \
                   ContactsProvider \
                   DefaultContainerService \
                   DeskClock \
                   DownloadProvider \
                   DownloadProviderUi \
                   DrmProvider \
                   Email \
                   Exchange2 \
                   Galaxy4 \
                   GalaxyS2Settings \
                   Gallery2 \
                   HoloSpiralWallpaper \
                   HTMLViewer \
                   InputDevices \
                   KeyChain \
                   LatinIME \
                   Launcher2 \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   Mms \
                   Music \
                   MusicFX \
                   NoiseField \
                   PackageInstaller \
                   PhaseBeam \
                   Phone \
                   PicoTts \
                   Provision \
                   QuickSearchBox \
                   SamsungServiceMode \
                   Settings \
                   SettingsProvider \
                   SharedStorageBackup \
                   SoundRecorder \
				   Stk \
                   Superuser \
                   SystemUI \
                   TelephonyProvider \
                   TvOut \
                   UserDictionaryProvider \
                   VideoEditor \
                   VisualizationWallpapers \
                   VoiceDialer \
                   VpnDialogs \
                   WAPPushManager
